// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.uc.mei.is;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentGenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StudentGen)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 phone = 3;</code>
     * @return The phone.
     */
    long getPhone();

    /**
     * <code>string gender = 4;</code>
     * @return The gender.
     */
    java.lang.String getGender();
    /**
     * <code>string gender = 4;</code>
     * @return The bytes for gender.
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>string birthDate = 5;</code>
     * @return The birthDate.
     */
    java.lang.String getBirthDate();
    /**
     * <code>string birthDate = 5;</code>
     * @return The bytes for birthDate.
     */
    com.google.protobuf.ByteString
        getBirthDateBytes();

    /**
     * <code>string registrationDate = 6;</code>
     * @return The registrationDate.
     */
    java.lang.String getRegistrationDate();
    /**
     * <code>string registrationDate = 6;</code>
     * @return The bytes for registrationDate.
     */
    com.google.protobuf.ByteString
        getRegistrationDateBytes();

    /**
     * <code>string address = 7;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 7;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string professor = 8;</code>
     * @return The professor.
     */
    java.lang.String getProfessor();
    /**
     * <code>string professor = 8;</code>
     * @return The bytes for professor.
     */
    com.google.protobuf.ByteString
        getProfessorBytes();
  }
  /**
   * Protobuf type {@code StudentGen}
   */
  public static final class StudentGen extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StudentGen)
      StudentGenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentGen.newBuilder() to construct.
    private StudentGen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentGen() {
      name_ = "";
      gender_ = "";
      birthDate_ = "";
      registrationDate_ = "";
      address_ = "";
      professor_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StudentGen();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentGen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              phone_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              birthDate_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              registrationDate_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              professor_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uc.mei.is.Student.internal_static_StudentGen_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uc.mei.is.Student.internal_static_StudentGen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uc.mei.is.Student.StudentGen.class, com.uc.mei.is.Student.StudentGen.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    private long phone_;
    /**
     * <code>int64 phone = 3;</code>
     * @return The phone.
     */
    @java.lang.Override
    public long getPhone() {
      return phone_;
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object gender_;
    /**
     * <code>string gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>string gender = 4;</code>
     * @return The bytes for gender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object birthDate_;
    /**
     * <code>string birthDate = 5;</code>
     * @return The birthDate.
     */
    @java.lang.Override
    public java.lang.String getBirthDate() {
      java.lang.Object ref = birthDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthDate_ = s;
        return s;
      }
    }
    /**
     * <code>string birthDate = 5;</code>
     * @return The bytes for birthDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthDateBytes() {
      java.lang.Object ref = birthDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGISTRATIONDATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object registrationDate_;
    /**
     * <code>string registrationDate = 6;</code>
     * @return The registrationDate.
     */
    @java.lang.Override
    public java.lang.String getRegistrationDate() {
      java.lang.Object ref = registrationDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registrationDate_ = s;
        return s;
      }
    }
    /**
     * <code>string registrationDate = 6;</code>
     * @return The bytes for registrationDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegistrationDateBytes() {
      java.lang.Object ref = registrationDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registrationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 7;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 7;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 7;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFESSOR_FIELD_NUMBER = 8;
    private volatile java.lang.Object professor_;
    /**
     * <code>string professor = 8;</code>
     * @return The professor.
     */
    @java.lang.Override
    public java.lang.String getProfessor() {
      java.lang.Object ref = professor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        professor_ = s;
        return s;
      }
    }
    /**
     * <code>string professor = 8;</code>
     * @return The bytes for professor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProfessorBytes() {
      java.lang.Object ref = professor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        professor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (phone_ != 0L) {
        output.writeInt64(3, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, birthDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registrationDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, registrationDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(professor_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, professor_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (phone_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, phone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(birthDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, birthDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registrationDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, registrationDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, address_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(professor_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, professor_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.uc.mei.is.Student.StudentGen)) {
        return super.equals(obj);
      }
      com.uc.mei.is.Student.StudentGen other = (com.uc.mei.is.Student.StudentGen) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getPhone()
          != other.getPhone()) return false;
      if (!getGender()
          .equals(other.getGender())) return false;
      if (!getBirthDate()
          .equals(other.getBirthDate())) return false;
      if (!getRegistrationDate()
          .equals(other.getRegistrationDate())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getProfessor()
          .equals(other.getProfessor())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhone());
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthDate().hashCode();
      hash = (37 * hash) + REGISTRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getRegistrationDate().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PROFESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getProfessor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.uc.mei.is.Student.StudentGen parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uc.mei.is.Student.StudentGen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.uc.mei.is.Student.StudentGen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uc.mei.is.Student.StudentGen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.uc.mei.is.Student.StudentGen prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StudentGen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StudentGen)
        com.uc.mei.is.Student.StudentGenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uc.mei.is.Student.internal_static_StudentGen_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uc.mei.is.Student.internal_static_StudentGen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uc.mei.is.Student.StudentGen.class, com.uc.mei.is.Student.StudentGen.Builder.class);
      }

      // Construct using com.uc.mei.is.Student.StudentGen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        phone_ = 0L;

        gender_ = "";

        birthDate_ = "";

        registrationDate_ = "";

        address_ = "";

        professor_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uc.mei.is.Student.internal_static_StudentGen_descriptor;
      }

      @java.lang.Override
      public com.uc.mei.is.Student.StudentGen getDefaultInstanceForType() {
        return com.uc.mei.is.Student.StudentGen.getDefaultInstance();
      }

      @java.lang.Override
      public com.uc.mei.is.Student.StudentGen build() {
        com.uc.mei.is.Student.StudentGen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.uc.mei.is.Student.StudentGen buildPartial() {
        com.uc.mei.is.Student.StudentGen result = new com.uc.mei.is.Student.StudentGen(this);
        result.id_ = id_;
        result.name_ = name_;
        result.phone_ = phone_;
        result.gender_ = gender_;
        result.birthDate_ = birthDate_;
        result.registrationDate_ = registrationDate_;
        result.address_ = address_;
        result.professor_ = professor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uc.mei.is.Student.StudentGen) {
          return mergeFrom((com.uc.mei.is.Student.StudentGen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uc.mei.is.Student.StudentGen other) {
        if (other == com.uc.mei.is.Student.StudentGen.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getPhone() != 0L) {
          setPhone(other.getPhone());
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.getBirthDate().isEmpty()) {
          birthDate_ = other.birthDate_;
          onChanged();
        }
        if (!other.getRegistrationDate().isEmpty()) {
          registrationDate_ = other.registrationDate_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getProfessor().isEmpty()) {
          professor_ = other.professor_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uc.mei.is.Student.StudentGen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uc.mei.is.Student.StudentGen) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long phone_ ;
      /**
       * <code>int64 phone = 3;</code>
       * @return The phone.
       */
      @java.lang.Override
      public long getPhone() {
        return phone_;
      }
      /**
       * <code>int64 phone = 3;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(long value) {
        
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 phone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>string gender = 4;</code>
       * @return The gender.
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gender = 4;</code>
       * @return The bytes for gender.
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 4;</code>
       * @param value The bytes for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthDate_ = "";
      /**
       * <code>string birthDate = 5;</code>
       * @return The birthDate.
       */
      public java.lang.String getBirthDate() {
        java.lang.Object ref = birthDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string birthDate = 5;</code>
       * @return The bytes for birthDate.
       */
      public com.google.protobuf.ByteString
          getBirthDateBytes() {
        java.lang.Object ref = birthDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string birthDate = 5;</code>
       * @param value The birthDate to set.
       * @return This builder for chaining.
       */
      public Builder setBirthDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        birthDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string birthDate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthDate() {
        
        birthDate_ = getDefaultInstance().getBirthDate();
        onChanged();
        return this;
      }
      /**
       * <code>string birthDate = 5;</code>
       * @param value The bytes for birthDate to set.
       * @return This builder for chaining.
       */
      public Builder setBirthDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        birthDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object registrationDate_ = "";
      /**
       * <code>string registrationDate = 6;</code>
       * @return The registrationDate.
       */
      public java.lang.String getRegistrationDate() {
        java.lang.Object ref = registrationDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          registrationDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string registrationDate = 6;</code>
       * @return The bytes for registrationDate.
       */
      public com.google.protobuf.ByteString
          getRegistrationDateBytes() {
        java.lang.Object ref = registrationDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registrationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string registrationDate = 6;</code>
       * @param value The registrationDate to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        registrationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string registrationDate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegistrationDate() {
        
        registrationDate_ = getDefaultInstance().getRegistrationDate();
        onChanged();
        return this;
      }
      /**
       * <code>string registrationDate = 6;</code>
       * @param value The bytes for registrationDate to set.
       * @return This builder for chaining.
       */
      public Builder setRegistrationDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        registrationDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 7;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 7;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 7;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 7;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object professor_ = "";
      /**
       * <code>string professor = 8;</code>
       * @return The professor.
       */
      public java.lang.String getProfessor() {
        java.lang.Object ref = professor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          professor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string professor = 8;</code>
       * @return The bytes for professor.
       */
      public com.google.protobuf.ByteString
          getProfessorBytes() {
        java.lang.Object ref = professor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          professor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string professor = 8;</code>
       * @param value The professor to set.
       * @return This builder for chaining.
       */
      public Builder setProfessor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        professor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string professor = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearProfessor() {
        
        professor_ = getDefaultInstance().getProfessor();
        onChanged();
        return this;
      }
      /**
       * <code>string professor = 8;</code>
       * @param value The bytes for professor to set.
       * @return This builder for chaining.
       */
      public Builder setProfessorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        professor_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StudentGen)
    }

    // @@protoc_insertion_point(class_scope:StudentGen)
    private static final com.uc.mei.is.Student.StudentGen DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.uc.mei.is.Student.StudentGen();
    }

    public static com.uc.mei.is.Student.StudentGen getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentGen>
        PARSER = new com.google.protobuf.AbstractParser<StudentGen>() {
      @java.lang.Override
      public StudentGen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentGen(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentGen> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentGen> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.uc.mei.is.Student.StudentGen getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentGen_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentGen_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\"\226\001\n\nStudentGen\022\n\n\002id\030\001 \001" +
      "(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005phone\030\003 \001(\003\022\016\n\006gende" +
      "r\030\004 \001(\t\022\021\n\tbirthDate\030\005 \001(\t\022\030\n\020registrati" +
      "onDate\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\021\n\tprofess" +
      "or\030\010 \001(\tB\017\n\rcom.uc.mei.isb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StudentGen_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StudentGen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentGen_descriptor,
        new java.lang.String[] { "Id", "Name", "Phone", "Gender", "BirthDate", "RegistrationDate", "Address", "Professor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
